### ISSUE TITLE
Add Prices to the vegies/fruits card

### ISSUE THREAD

**Issue by jainaayush01** [adi-g15/EasyLife-GroceryStore#1]
Add Prices to the Vegetable and fruit card so that the user can get to know about the price

**Comment by adi-g15** [comment]
Thanks for creating this issue, actually it is there, but it was too light, and after changing the default image ab it's not clearly visible.

https://github.com/adi-g15/EasyLife-GroceryStore/blob/26c3abaa0207f4151a9d43ec8a9ca46a530c3edc/src/components/sabjibox.jsx#L89-L99

**If you intend to modify yourself**, here it is, you may create a PR since you noticed, or i will change it myself 😃👍

**Comment by adi-g15** [comment]
With
color: 'black'; /*or rgb(0,0,0)*/
backgroundColor: rgba(255, 255, 255, 0.8);

It looks like this - 
![image](https://user-images.githubusercontent.com/37269665/104486159-5f57c900-55f1-11eb-9d1c-84c234db86c6.png)

Currently it's this - 
![image](https://user-images.githubusercontent.com/37269665/104486252-7dbdc480-55f1-11eb-8c25-7ec9decd870e.png)

**Comment by adi-g15** [comment]
Since there hasn't been a reply, i will fix it up 🙂

**Comment by jainaayush01** [comment]
Ohh The email was not read by me it was missed by me.
Sorry for not answering to the email.
It's totally fine whoever fix it.

**Comment by adi-g15** [comment]
Okay, it's fixed 😅
